 server:
   port: 8088
 spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pet?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root
    jpa:
      properties:
        hibernate:
          hbm2ddl:
             auto: update





  http:
    multipart:
        enabled: true
    max-file-size: 2048MB
    max-request-size: 2048MB
    maxPostSize: 0
  jackson:
    date-format:
        yyyy-MM-dd
    time-zone:
        GMT+8
 prop:
   upload-folder: E:\petspringboot\file\
   upload-video: E:\petspringboot\video\

